const {test}=require('node:test');const assert=require('node:assert/strict');const {notify,messages}=require('../lib/notifications');
const row={request_id:'test-id',name:'Test <Rider>',email:'guest@example.com',phone:'',edition:'october',room:'private',bike_rental:true,notes:'Private notes',indicative_price:1359};
const env={RESEND_API_KEY:'test',EMAIL_FROM:'Host <bookings@example.com>',NOTIFICATION_EMAIL:'host@example.com'};
test('separate host and guest messages use correct prices, replies and no confirmed-booking promise',()=>{const [host,guest]=messages(row,env);assert.deepEqual(host.to,['host@example.com']);assert.deepEqual(guest.to,['guest@example.com']);assert.equal(host.reply_to,row.email);assert.equal(guest.reply_to,env.NOTIFICATION_EMAIL);assert.match(guest.text,/€1359/);assert.match(guest.text,/does not reserve a place/);assert.ok(!guest.text.includes('Private notes'));assert.equal(guest.html,undefined);assert.match(messages({...row,edition:'may',indicative_price:null},env)[1].text,/Individual quote required/);});
test('email failures are isolated and both messages have independent retry keys',async()=>{const old=global.fetch;let calls=[];global.fetch=async(u,o)=>{calls.push(o);if(calls.length===1)throw Error('offline');return {ok:false,status:429};};try{await notify(row,env);assert.equal(calls.length,2);assert.notEqual(calls[0].headers['Idempotency-Key'],calls[1].headers['Idempotency-Key']);}finally{global.fetch=old;}});
test('stored requests succeed despite email failure; duplicate requests send no mail',async()=>{
 const handler=require('../api/register');const old=global.fetch;let duplicate=false,mails=0;
 const settings={...env,REGISTRATION_ENABLED:'true',SITE_ORIGIN:'https://camp.example',SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test',TURNSTILE_SITE_KEY:'test',TURNSTILE_SECRET_KEY:'test'};
 const body={request_id:'bf6c96e9-83e5-4d91-92bd-058eff48c652',name:'Test',email:'guest@example.com',phone:'',notes:'',edition:'may',room:'shared',bike_rental:false,consent:true,website:'',turnstile_token:'test'};
 global.fetch=async(url,options)=>{if(url.includes('siteverify'))return {ok:true,json:async()=>({success:true,hostname:'camp.example',action:'booking'})};if(url.includes('supabase.co'))return {ok:true,json:async()=>duplicate?[]:[JSON.parse(options.body)]};mails++;return {ok:false,status:503};};
 const response=()=>({setHeader(){},status(code){this.code=code;return this;},json(data){this.data=data;return this;}});
 try{let res=response();await handler({method:'POST',headers:{origin:settings.SITE_ORIGIN,'content-type':'application/json'},body},res,settings);assert.equal(res.code,200);assert.equal(res.data.ok,true);assert.equal(mails,2);duplicate=true;res=response();await handler({method:'POST',headers:{origin:settings.SITE_ORIGIN,'content-type':'application/json'},body},res,settings);assert.equal(res.code,200);assert.equal(mails,2);}finally{global.fetch=old;}
});
