const {test}=require('node:test'),assert=require('node:assert/strict');
const offer=require('../offer'),{config,ready}=require('../lib/config');
const base=config({});const start=Date.parse(base.privateOpens),end=Date.parse(base.privateDeadline);
test('release boundaries have no dead booking window',()=>{assert.equal(offer.state(base,start-1),'before_private');assert.equal(offer.state(base,start),'private_open');assert.equal(offer.state({...base,privateBooked:4,totalBooked:4},start),'list_standard');assert.equal(offer.state(base,end),'public_open');assert.equal(end-start,72*3600000);});
test('fully booked overrides every release',()=>{assert.equal(offer.state({...base,totalBooked:10,privateBooked:4},start),'sold_out');});
test('invalid counters fail closed',()=>{for(const c of [{totalBooked:11},{privateBooked:5},{totalBooked:2,privateBooked:4},{totalBooked:NaN}])assert.equal(offer.state({...base,...c},start),'unconfigured');});
test('single room pricing includes supplement in totals and balances',()=>{assert.equal(offer.price('private','single'),1359);assert.equal(offer.price('standard','single')-150,1309);assert.equal(offer.price('private','shared')-150,849);});
const live={...base,releaseConfirmed:true,packageConfirmed:true,termsConfirmed:true,limitsConfirmed:true,termsUrl:'https://example.com/terms',allocations:[{id:'private_shared',tier:'private',room:'shared',cap:4,paid:0,url:'https://checkout.revolut.com/pay/test-one'},{id:'standard_shared',tier:'standard',room:'shared',cap:6,paid:0,url:'https://checkout.revolut.com/pay/test-two'}]};
test('readiness requires explicit confirmations and provider caps',()=>{assert.equal(ready(base),false);assert.equal(ready(live),true);for(const key of ['releaseConfirmed','packageConfirmed','termsConfirmed','limitsConfirmed'])assert.equal(ready({...live,[key]:false}),false);});
test('quotas cannot duplicate links or exceed 4 discounted / 10 total',()=>{assert.equal(ready({...live,allocations:[{...live.allocations[0],cap:10}]}),false);assert.equal(ready({...live,allocations:[...live.allocations,{id:'extra',tier:'standard',room:'single',cap:1,paid:0,url:'https://checkout.revolut.com/pay/extra'}]}),false);assert.equal(ready({...live,allocations:[live.allocations[0],{...live.allocations[1],url:live.allocations[0].url}]}),false);});
test('untrusted checkout domains rejected',()=>{assert.equal(offer.validLink('https://checkout.revolut.com.evil.test/x'),false);assert.equal(offer.validLink('javascript:alert(1)'),false);assert.equal(offer.validLink('https://checkout.revolut.com/pay/test'),true);});
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.data=v;return this;}};}
test('checkout cannot bypass missing launch configuration',async()=>{const r=response();await require('../api/checkout')({method:'POST',body:{option:'private_shared',termsAccepted:true}},r);assert.equal(r.code,409);assert.equal(r.data.ok,false);});
test('enquiry rejects missing email and disconnected endpoint',async()=>{const api=require('../api/register');let r=response();await api({method:'POST',body:{}},r);assert.equal(r.code,400);r=response();await api({method:'POST',body:{name:'Test',email:'test@example.com',consent:'Yes',request_id:'00000000-0000-0000-0000-000000000000'}},r);assert.equal(r.code,503);});
test('confirmation page never claims payment from a query string',()=>{const html=require('node:fs').readFileSync(require('node:path').join(__dirname,'../thanks.html'),'utf8');assert.ok(!html.includes('deposit_paid'));assert.ok(!html.includes('URLSearchParams'));assert.ok(html.includes('does not verify a payment'));});
test('enquiry only acknowledges a verified upstream write and preserves request ID',async()=>{
 const originalFetch=global.fetch,oldUrl=process.env.APPS_SCRIPT_URL,oldSecret=process.env.FORM_SHARED_SECRET;
 process.env.APPS_SCRIPT_URL='https://script.google.com/macros/s/test/exec';process.env.FORM_SHARED_SECRET='test-only';
 const body={name:'Test',email:'test@example.com',consent:'Yes',bike_rental:'Yes',request_id:'11111111-1111-1111-1111-111111111111'};
 try{global.fetch=async()=>({ok:true,json:async()=>({ok:false})});let r=response();await require('../api/register')({method:'POST',body},r);assert.equal(r.code,502);
 global.fetch=async(url,options)=>{assert.equal(JSON.parse(options.body.get('payload')).bike_rental,'Yes');return {ok:true,json:async()=>({ok:true,request_id:body.request_id})};};r=response();await require('../api/register')({method:'POST',body},r);assert.equal(r.code,200);assert.equal(r.data.request_id,body.request_id);
 }finally{global.fetch=originalFetch;if(oldUrl===undefined)delete process.env.APPS_SCRIPT_URL;else process.env.APPS_SCRIPT_URL=oldUrl;if(oldSecret===undefined)delete process.env.FORM_SHARED_SECRET;else process.env.FORM_SHARED_SECRET=oldSecret;}
});
